version: '2.1'
services:
  db:
    image: postgres:13
    ports:
      - "5434:5432"
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: G!dvWTEUHd^+
      POSTGRES_DB: fun-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5